<?php
session_start();
require_once "authentication/database.php";
require_once "authentication/get_config.php";
require_once "include/translation_helpers.php";

$fullName = $_SESSION["user"]["full_name"] ?? "Guest";
$role = $_SESSION["user"]["role"] ?? "guest";
$GLOBALS['header_user_full_name'] = $fullName;
$GLOBALS['header_user_role'] = $role;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Service - Creations by Athina</title>
    <link rel="stylesheet" href="assets/styling/styles.css?v=<?= (int)@filemtime(__DIR__ . '/assets/styling/styles.css') ?>">
    <link rel="stylesheet" href="assets/styling/header.css?v=<?= (int)@filemtime(__DIR__ . '/assets/styling/header.css') ?>">
    <link rel="stylesheet" href="assets/styling/info_pages.css?v=<?= (int)@filemtime(__DIR__ . '/assets/styling/info_pages.css') ?>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="assets/js/translations.js?v=<?= (int)@filemtime(__DIR__ . '/assets/js/translations.js') ?>" defer></script>
</head>
<body class="site-page"<?= app_translate_page_title_attrs('Terms of Service - Creations by Athina', 'Όροι Χρήσης - Creations by Athina') ?>>
<?php
$activePage = '';
include __DIR__ . '/include/header.php';
?>

<main class="info-page">
    <section class="info-hero">
        <div class="container">
            <h1<?= app_translate_text_attrs('Terms of Service', 'Όροι Χρήσης') ?>>Terms of Service</h1>
            <p<?= app_translate_text_attrs('These terms explain how the Creations by Athina website works, what customers can expect when they browse or place an order, and the rules that help the shop operate fairly and safely.', 'Αυτοί οι όροι εξηγούν πώς λειτουργεί το website του Creations by Athina, τι μπορούν να περιμένουν οι πελάτες όταν περιηγούνται ή πραγματοποιούν παραγγελία και ποιους κανόνες ακολουθεί το κατάστημα για να λειτουργεί δίκαια και με ασφάλεια.') ?>>These terms explain how the Creations by Athina website works, what customers can expect when they browse or place an order, and the rules that help the shop operate fairly and safely.</p>
        </div>
    </section>

    <section class="info-content">
        <div class="container">
            <div class="info-stack">
                <article class="info-card">
                    <h2<?= app_translate_text_attrs('1. Using the Website', '1. Χρήση του Website') ?>>1. Using the Website</h2>
                    <p<?= app_translate_text_attrs('By visiting, browsing, creating an account, or placing an order on Creations by Athina, you agree to use the website only for lawful shopping, account, and communication purposes. Misuse of forms, checkout tools, account features, review systems, or security measures may lead to order cancellation, account restrictions, or blocked access.', 'Με την επίσκεψη, την περιήγηση, τη δημιουργία λογαριασμού ή την υποβολή παραγγελίας στο Creations by Athina, συμφωνείτε να χρησιμοποιείτε το website μόνο για νόμιμους σκοπούς αγορών, λογαριασμού και επικοινωνίας. Κακή χρήση φορμών, εργαλείων checkout, λειτουργιών λογαριασμού, συστημάτων αξιολόγησης ή μέτρων ασφαλείας μπορεί να οδηγήσει σε ακύρωση παραγγελίας, περιορισμούς λογαριασμού ή αποκλεισμό πρόσβασης.') ?>>By visiting, browsing, creating an account, or placing an order on Creations by Athina, you agree to use the website only for lawful shopping, account, and communication purposes. Misuse of forms, checkout tools, account features, review systems, or security measures may lead to order cancellation, account restrictions, or blocked access.</p>
                    <p<?= app_translate_text_attrs('The website content is provided to help customers discover handmade crochet products, request support, and complete purchases. Nothing on the website should be used in a way that damages the shop, other customers, or the normal operation of the platform.', 'Το περιεχόμενο του website παρέχεται ώστε οι πελάτες να ανακαλύπτουν χειροποίητα crochet προϊόντα, να ζητούν υποστήριξη και να ολοκληρώνουν αγορές. Τίποτα στο website δεν πρέπει να χρησιμοποιείται με τρόπο που βλάπτει το κατάστημα, άλλους πελάτες ή την ομαλή λειτουργία της πλατφόρμας.') ?>>The website content is provided to help customers discover handmade crochet products, request support, and complete purchases. Nothing on the website should be used in a way that damages the shop, other customers, or the normal operation of the platform.</p>
                </article>

                <article class="info-card">
                    <h2<?= app_translate_text_attrs('2. Handmade Products and Product Information', '2. Χειροποίητα Προϊόντα και Πληροφορίες Προϊόντων') ?>>2. Handmade Products and Product Information</h2>
                    <p<?= app_translate_text_attrs('Creations by Athina specializes in handmade crochet items. Because products are handmade, small differences in shape, stitching, yarn tone, stuffing, finish, or dimensions can naturally happen from one piece to another. These differences are a normal part of handmade work and are not automatically considered defects.', 'Το Creations by Athina ειδικεύεται σε χειροποίητα crochet προϊόντα. Επειδή τα προϊόντα είναι χειροποίητα, μικρές διαφορές σε σχήμα, ραφές, απόχρωση νήματος, γέμισμα, τελείωμα ή διαστάσεις μπορεί φυσιολογικά να εμφανίζονται από κομμάτι σε κομμάτι. Αυτές οι διαφορές αποτελούν φυσιολογικό μέρος της χειροποίητης εργασίας και δεν θεωρούνται αυτόματα ελαττώματα.') ?>>Creations by Athina specializes in handmade crochet items. Because products are handmade, small differences in shape, stitching, yarn tone, stuffing, finish, or dimensions can naturally happen from one piece to another. These differences are a normal part of handmade work and are not automatically considered defects.</p>
                    <p<?= app_translate_text_attrs('Product photographs, descriptions, and measurements are presented as accurately as possible, but colors may appear slightly different depending on lighting, editing, yarn batches, or screen settings. Where a product is marked as made to order, custom, or low stock, production times and final details may vary from ready-to-ship items.', 'Οι φωτογραφίες, οι περιγραφές και οι διαστάσεις των προϊόντων παρουσιάζονται όσο το δυνατόν πιο ακριβώς, αλλά τα χρώματα μπορεί να φαίνονται ελαφρώς διαφορετικά ανάλογα με τον φωτισμό, την επεξεργασία, τις παρτίδες νήματος ή τις ρυθμίσεις οθόνης. Όταν ένα προϊόν επισημαίνεται ως made to order, custom ή με χαμηλό απόθεμα, οι χρόνοι παραγωγής και οι τελικές λεπτομέρειες μπορεί να διαφέρουν από τα έτοιμα προς αποστολή προϊόντα.') ?>>Product photographs, descriptions, and measurements are presented as accurately as possible, but colors may appear slightly different depending on lighting, editing, yarn batches, or screen settings. Where a product is marked as made to order, custom, or low stock, production times and final details may vary from ready-to-ship items.</p>
                </article>

                <article class="info-card">
                    <h2<?= app_translate_text_attrs('3. Orders, Availability, and Acceptance', '3. Παραγγελίες, Διαθεσιμότητα και Αποδοχή') ?>>3. Orders, Availability, and Acceptance</h2>
                    <p<?= app_translate_text_attrs('All orders are subject to product availability, payment approval, pricing accuracy, and review by the shop where needed. Adding an item to the cart or completing checkout does not automatically guarantee final acceptance if a stock issue, pricing error, shipping limitation, or custom-order clarification still needs to be resolved.', 'Όλες οι παραγγελίες υπόκεινται σε διαθεσιμότητα προϊόντων, έγκριση πληρωμής, ορθότητα τιμών και έλεγχο από το κατάστημα όπου χρειάζεται. Η προσθήκη προϊόντος στο καλάθι ή η ολοκλήρωση του checkout δεν εγγυάται αυτόματα τελική αποδοχή αν πρέπει ακόμη να επιλυθεί θέμα αποθέματος, λάθος τιμής, περιορισμός αποστολής ή διευκρίνιση custom παραγγελίας.') ?>>All orders are subject to product availability, payment approval, pricing accuracy, and review by the shop where needed. Adding an item to the cart or completing checkout does not automatically guarantee final acceptance if a stock issue, pricing error, shipping limitation, or custom-order clarification still needs to be resolved.</p>
                    <p<?= app_translate_text_attrs('If the shop needs to confirm product details, delivery information, personalization choices, or order eligibility, the customer may be contacted before the order is fully processed. The shop reserves the right to refuse, limit, or cancel an order when necessary for security, stock, fulfillment, or fraud-prevention reasons.', 'Αν το κατάστημα χρειάζεται να επιβεβαιώσει λεπτομέρειες προϊόντος, πληροφορίες παράδοσης, επιλογές προσωποποίησης ή την καταλληλότητα μιας παραγγελίας, ο πελάτης μπορεί να ενημερωθεί πριν η παραγγελία επεξεργαστεί πλήρως. Το κατάστημα διατηρεί το δικαίωμα να αρνηθεί, να περιορίσει ή να ακυρώσει μια παραγγελία όταν αυτό είναι απαραίτητο για λόγους ασφαλείας, αποθέματος, εκτέλεσης ή πρόληψης απάτης.') ?>>If the shop needs to confirm product details, delivery information, personalization choices, or order eligibility, the customer may be contacted before the order is fully processed. The shop reserves the right to refuse, limit, or cancel an order when necessary for security, stock, fulfillment, or fraud-prevention reasons.</p>
                </article>

                <article class="info-card">
                    <h2<?= app_translate_text_attrs('4. Prices, Payments, and Checkout', '4. Τιμές, Πληρωμές και Checkout') ?>>4. Prices, Payments, and Checkout</h2>
                    <p<?= app_translate_text_attrs('Prices shown on the website are listed in the currency displayed at checkout and may change without notice before an order is placed. Shipping fees, discounts, coupon effects, loyalty redemptions, taxes where applicable, and payment-method fees are determined by the checkout flow active at the time of purchase.', 'Οι τιμές που εμφανίζονται στο website παρουσιάζονται στο νόμισμα που φαίνεται στο checkout και μπορεί να αλλάξουν χωρίς προειδοποίηση πριν την υποβολή μιας παραγγελίας. Τα έξοδα αποστολής, οι εκπτώσεις, η επίδραση κουπονιών, οι εξαργυρώσεις loyalty, οι φόροι όπου εφαρμόζονται και οι χρεώσεις τρόπου πληρωμής καθορίζονται από τη ροή checkout που ισχύει τη στιγμή της αγοράς.') ?>>Prices shown on the website are listed in the currency displayed at checkout and may change without notice before an order is placed. Shipping fees, discounts, coupon effects, loyalty redemptions, taxes where applicable, and payment-method fees are determined by the checkout flow active at the time of purchase.</p>
                    <p<?= app_translate_text_attrs('Payment must be successfully authorized before an order can move into fulfillment. Creations by Athina may use integrated payment providers such as Stripe or PayPal. Customers are responsible for providing accurate billing and contact information so payment and order confirmation can be completed correctly.', 'Η πληρωμή πρέπει να εγκριθεί επιτυχώς πριν μια παραγγελία προχωρήσει σε εκτέλεση. Το Creations by Athina μπορεί να χρησιμοποιεί ενσωματωμένους παρόχους πληρωμών όπως Stripe ή PayPal. Οι πελάτες είναι υπεύθυνοι να παρέχουν ακριβή στοιχεία χρέωσης και επικοινωνίας ώστε η πληρωμή και η επιβεβαίωση της παραγγελίας να ολοκληρώνονται σωστά.') ?>>Payment must be successfully authorized before an order can move into fulfillment. Creations by Athina may use integrated payment providers such as Stripe or PayPal. Customers are responsible for providing accurate billing and contact information so payment and order confirmation can be completed correctly.</p>
                </article>

                <article class="info-card">
                    <h2<?= app_translate_text_attrs('5. Custom Orders and Made-to-Order Work', '5. Custom Παραγγελίες και Made-to-Order Εργασίες') ?>>5. Custom Orders and Made-to-Order Work</h2>
                    <p<?= app_translate_text_attrs('Custom requests, private checkout links, and made-to-order products may require direct communication with the shop before purchase. Production cannot begin until the relevant design, price, timeline, and payment requirements are clearly agreed. Handmade custom work may not be refundable once materials have been committed or production has started, except where required by applicable law.', 'Τα custom αιτήματα, οι ιδιωτικοί σύνδεσμοι checkout και τα made-to-order προϊόντα μπορεί να απαιτούν άμεση επικοινωνία με το κατάστημα πριν την αγορά. Η παραγωγή δεν μπορεί να ξεκινήσει μέχρι να συμφωνηθούν ξεκάθαρα ο σχεδιασμός, η τιμή, το χρονοδιάγραμμα και οι απαιτήσεις πληρωμής. Οι χειροποίητες custom εργασίες μπορεί να μην επιστρέφονται αφού δεσμευτούν υλικά ή ξεκινήσει η παραγωγή, εκτός όπου απαιτείται από την ισχύουσα νομοθεσία.') ?>>Custom requests, private checkout links, and made-to-order products may require direct communication with the shop before purchase. Production cannot begin until the relevant design, price, timeline, and payment requirements are clearly agreed. Handmade custom work may not be refundable once materials have been committed or production has started, except where required by applicable law.</p>
                    <p<?= app_translate_text_attrs('Customers are responsible for reviewing their requested details carefully before confirming a custom or personalized order. The shop may decline custom work that is unclear, impractical, unsafe, or outside the shop\'s creative and operational scope.', 'Οι πελάτες είναι υπεύθυνοι να ελέγχουν προσεκτικά τις ζητούμενες λεπτομέρειες πριν επιβεβαιώσουν custom ή προσωποποιημένη παραγγελία. Το κατάστημα μπορεί να αρνηθεί custom εργασία που είναι ασαφής, μη πρακτική, μη ασφαλής ή εκτός του δημιουργικού και λειτουργικού πλαισίου του.') ?>>Customers are responsible for reviewing their requested details carefully before confirming a custom or personalized order. The shop may decline custom work that is unclear, impractical, unsafe, or outside the shop's creative and operational scope.</p>
                </article>

                <article class="info-card">
                    <h2<?= app_translate_text_attrs('6. Shipping, Delivery, and Customer Responsibility', '6. Αποστολή, Παράδοση και Ευθύνη Πελάτη') ?>>6. Shipping, Delivery, and Customer Responsibility</h2>
                    <p<?= app_translate_text_attrs('Shipping times are estimates unless the shop clearly confirms otherwise. Delays can happen because of courier schedules, customs processing, seasonal demand, address problems, or events outside the shop\'s control. Customers are responsible for entering correct shipping details and for monitoring delivery updates after dispatch.', 'Οι χρόνοι αποστολής είναι εκτιμώμενοι εκτός αν το κατάστημα επιβεβαιώσει ξεκάθαρα κάτι διαφορετικό. Καθυστερήσεις μπορεί να προκύψουν λόγω προγραμμάτων courier, τελωνειακής επεξεργασίας, εποχικής ζήτησης, προβλημάτων διεύθυνσης ή γεγονότων εκτός του ελέγχου του καταστήματος. Οι πελάτες είναι υπεύθυνοι να εισάγουν σωστά στοιχεία αποστολής και να παρακολουθούν τις ενημερώσεις παράδοσης μετά την αποστολή.') ?>>Shipping times are estimates unless the shop clearly confirms otherwise. Delays can happen because of courier schedules, customs processing, seasonal demand, address problems, or events outside the shop's control. Customers are responsible for entering correct shipping details and for monitoring delivery updates after dispatch.</p>
                    <p<?= app_translate_text_attrs('If a parcel is delayed, returned, unclaimed, or affected by a courier issue, the shop will make reasonable efforts to help, but courier operations remain outside the shop\'s direct control. Extra costs caused by incorrect address details, refused delivery, or re-shipment needs may be charged to the customer when appropriate.', 'Αν ένα δέμα καθυστερήσει, επιστραφεί, μείνει αζήτητο ή επηρεαστεί από ζήτημα courier, το κατάστημα θα καταβάλει εύλογες προσπάθειες να βοηθήσει, όμως οι λειτουργίες των courier παραμένουν εκτός του άμεσου ελέγχου του. Επιπλέον κόστη που προκαλούνται από λανθασμένα στοιχεία διεύθυνσης, άρνηση παραλαβής ή ανάγκη επαναποστολής μπορεί να χρεωθούν στον πελάτη όπου κρίνεται κατάλληλο.') ?>>If a parcel is delayed, returned, unclaimed, or affected by a courier issue, the shop will make reasonable efforts to help, but courier operations remain outside the shop's direct control. Extra costs caused by incorrect address details, refused delivery, or re-shipment needs may be charged to the customer when appropriate.</p>
                </article>

                <article class="info-card">
                    <h2<?= app_translate_text_attrs('7. Returns, Cancellations, and Refunds', '7. Επιστροφές, Ακυρώσεις και Επιστροφές Χρημάτων') ?>>7. Returns, Cancellations, and Refunds</h2>
                    <p<?= app_translate_text_attrs('Returns, cancellations, and refunds are handled according to the shop\'s posted policy, product condition, and any legal rights that apply to the customer. Ready-made items may be eligible for return if they are unused, returned in acceptable condition, and requested within the stated return window. Personalized, custom, intimate-use, or clearly made-to-order items may be excluded from return where the law allows.', 'Οι επιστροφές, οι ακυρώσεις και οι επιστροφές χρημάτων διαχειρίζονται σύμφωνα με την αναρτημένη πολιτική του καταστήματος, την κατάσταση του προϊόντος και τυχόν νόμιμα δικαιώματα που ισχύουν για τον πελάτη. Τα έτοιμα προϊόντα μπορεί να είναι επιλέξιμα για επιστροφή αν είναι αχρησιμοποίητα, επιστραφούν σε αποδεκτή κατάσταση και ζητηθούν μέσα στο δηλωμένο χρονικό περιθώριο επιστροφής. Τα προσωποποιημένα, custom, προσωπικής χρήσης ή σαφώς made-to-order προϊόντα μπορεί να εξαιρούνται από επιστροφή όπου το επιτρέπει ο νόμος.') ?>>Returns, cancellations, and refunds are handled according to the shop's posted policy, product condition, and any legal rights that apply to the customer. Ready-made items may be eligible for return if they are unused, returned in acceptable condition, and requested within the stated return window. Personalized, custom, intimate-use, or clearly made-to-order items may be excluded from return where the law allows.</p>
                    <p<?= app_translate_text_attrs('If an order needs to be cancelled, the customer should contact the shop as quickly as possible. Once an order has entered production, packing, or shipment, cancellation options may become limited. Approved refunds are normally returned through the original payment route unless another method is legally required or mutually agreed.', 'Αν μια παραγγελία χρειάζεται να ακυρωθεί, ο πελάτης πρέπει να επικοινωνήσει με το κατάστημα όσο το δυνατόν γρηγορότερα. Μόλις μια παραγγελία περάσει σε παραγωγή, συσκευασία ή αποστολή, οι επιλογές ακύρωσης μπορεί να είναι περιορισμένες. Οι εγκεκριμένες επιστροφές χρημάτων συνήθως επιστρέφονται μέσω της αρχικής μεθόδου πληρωμής, εκτός αν απαιτείται διαφορετικά από τον νόμο ή υπάρξει αμοιβαία συμφωνία.') ?>>If an order needs to be cancelled, the customer should contact the shop as quickly as possible. Once an order has entered production, packing, or shipment, cancellation options may become limited. Approved refunds are normally returned through the original payment route unless another method is legally required or mutually agreed.</p>
                </article>

                <article class="info-card">
                    <h2<?= app_translate_text_attrs('8. Accounts, Security, and Fair Use', '8. Λογαριασμοί, Ασφάλεια και Ορθή Χρήση') ?>>8. Accounts, Security, and Fair Use</h2>
                    <p<?= app_translate_text_attrs('If you create an account, you are responsible for keeping your login details accurate and secure. The website may use session, security, device, and authentication cookies or similar technologies that are strictly necessary for secure login, fraud prevention, cart continuity, and order completion.', 'Αν δημιουργήσετε λογαριασμό, είστε υπεύθυνοι να διατηρείτε τα στοιχεία σύνδεσής σας ακριβή και ασφαλή. Το website μπορεί να χρησιμοποιεί cookies ή παρόμοιες τεχνολογίες συνεδρίας, ασφάλειας, συσκευής και πιστοποίησης που είναι απολύτως απαραίτητες για ασφαλή σύνδεση, πρόληψη απάτης, διατήρηση καλαθιού και ολοκλήρωση παραγγελίας.') ?>>If you create an account, you are responsible for keeping your login details accurate and secure. The website may use session, security, device, and authentication cookies or similar technologies that are strictly necessary for secure login, fraud prevention, cart continuity, and order completion.</p>
                    <p<?= app_translate_text_attrs('You must not attempt to bypass security features, interfere with checkout, scrape product or customer data, upload harmful material, abuse discount systems, or impersonate another person. Accounts or orders connected to suspicious or abusive behavior may be suspended, reviewed, or cancelled.', 'Δεν πρέπει να επιχειρείτε να παρακάμψετε λειτουργίες ασφαλείας, να παρεμβαίνετε στο checkout, να εξάγετε δεδομένα προϊόντων ή πελατών, να ανεβάζετε επιβλαβές υλικό, να καταχράστε συστήματα εκπτώσεων ή να προσποιείστε άλλο πρόσωπο. Λογαριασμοί ή παραγγελίες που συνδέονται με ύποπτη ή καταχρηστική συμπεριφορά μπορεί να ανασταλούν, να ελεγχθούν ή να ακυρωθούν.') ?>>You must not attempt to bypass security features, interfere with checkout, scrape product or customer data, upload harmful material, abuse discount systems, or impersonate another person. Accounts or orders connected to suspicious or abusive behavior may be suspended, reviewed, or cancelled.</p>
                </article>

                <article class="info-card">
                    <h2<?= app_translate_text_attrs('9. Intellectual Property', '9. Πνευματική Ιδιοκτησία') ?>>9. Intellectual Property</h2>
                    <p<?= app_translate_text_attrs('Website content, product photography, brand presentation, written descriptions, logos, graphics, and original handmade product designs remain the property of Creations by Athina or their respective rights holders unless stated otherwise. You may browse and use the website for personal shopping purposes, but you may not copy, republish, sell, or reuse protected content without permission.', 'Το περιεχόμενο του website, οι φωτογραφίες προϊόντων, η παρουσίαση του brand, οι γραπτές περιγραφές, τα λογότυπα, τα γραφικά και τα πρωτότυπα χειροποίητα σχέδια προϊόντων παραμένουν ιδιοκτησία του Creations by Athina ή των αντίστοιχων δικαιούχων τους, εκτός αν δηλώνεται διαφορετικά. Μπορείτε να περιηγείστε και να χρησιμοποιείτε το website για προσωπικούς σκοπούς αγορών, αλλά δεν επιτρέπεται να αντιγράφετε, να αναδημοσιεύετε, να πουλάτε ή να επαναχρησιμοποιείτε προστατευόμενο περιεχόμενο χωρίς άδεια.') ?>>Website content, product photography, brand presentation, written descriptions, logos, graphics, and original handmade product designs remain the property of Creations by Athina or their respective rights holders unless stated otherwise. You may browse and use the website for personal shopping purposes, but you may not copy, republish, sell, or reuse protected content without permission.</p>
                </article>

                <article class="info-card">
                    <h2<?= app_translate_text_attrs('10. Liability and Legal Rights', '10. Ευθύνη και Νομικά Δικαιώματα') ?>>10. Liability and Legal Rights</h2>
                    <p<?= app_translate_text_attrs('Creations by Athina works to keep product information, pricing, stock status, and website features accurate, but occasional errors or interruptions may still happen. To the fullest extent permitted by law, the shop is not responsible for indirect losses, third-party service outages, courier failures, payment-network downtime, or customer losses caused by incorrect information supplied during checkout.', 'Το Creations by Athina προσπαθεί να διατηρεί ακριβείς τις πληροφορίες προϊόντων, τις τιμές, την κατάσταση αποθέματος και τις λειτουργίες του website, αλλά ενδέχεται να προκύψουν περιστασιακά λάθη ή διακοπές. Στο μέγιστο βαθμό που επιτρέπεται από τον νόμο, το κατάστημα δεν ευθύνεται για έμμεσες απώλειες, διακοπές υπηρεσιών τρίτων, αποτυχίες courier, διακοπές δικτύων πληρωμών ή απώλειες πελατών που προκαλούνται από λανθασμένες πληροφορίες που δόθηκαν κατά το checkout.') ?>>Creations by Athina works to keep product information, pricing, stock status, and website features accurate, but occasional errors or interruptions may still happen. To the fullest extent permitted by law, the shop is not responsible for indirect losses, third-party service outages, courier failures, payment-network downtime, or customer losses caused by incorrect information supplied during checkout.</p>
                    <p<?= app_translate_text_attrs('Nothing in these terms removes or limits any mandatory consumer rights that apply under relevant law. If a local law gives the customer stronger protection than a clause on this page, that legal protection continues to apply.', 'Τίποτα σε αυτούς τους όρους δεν αφαιρεί ή περιορίζει υποχρεωτικά δικαιώματα καταναλωτή που ισχύουν σύμφωνα με τη σχετική νομοθεσία. Αν κάποιος τοπικός νόμος παρέχει στον πελάτη ισχυρότερη προστασία από κάποια ρήτρα αυτής της σελίδας, η νομική αυτή προστασία εξακολουθεί να ισχύει.') ?>>Nothing in these terms removes or limits any mandatory consumer rights that apply under relevant law. If a local law gives the customer stronger protection than a clause on this page, that legal protection continues to apply.</p>
                </article>

                <article class="info-card">
                    <h2<?= app_translate_text_attrs('11. Policy Changes and Contact', '11. Αλλαγές Πολιτικής και Επικοινωνία') ?>>11. Policy Changes and Contact</h2>
                    <p<?= app_translate_text_attrs('These terms may be updated from time to time to reflect changes in the business, legal requirements, delivery processes, or website functionality. The version published on the website at the time of use or purchase is the version that applies unless the law requires something different.', 'Αυτοί οι όροι μπορεί να ενημερώνονται κατά καιρούς ώστε να αντικατοπτρίζουν αλλαγές στην επιχείρηση, στις νομικές απαιτήσεις, στις διαδικασίες παράδοσης ή στη λειτουργικότητα του website. Η έκδοση που δημοσιεύεται στο website κατά τη στιγμή της χρήσης ή της αγοράς είναι η έκδοση που ισχύει, εκτός αν ο νόμος απαιτεί κάτι διαφορετικό.') ?>>These terms may be updated from time to time to reflect changes in the business, legal requirements, delivery processes, or website functionality. The version published on the website at the time of use or purchase is the version that applies unless the law requires something different.</p>
                    <p<?= app_translate_text_attrs('If you have a question about an order, a policy detail, or how the website works, please use the contact page so the shop can assist directly before you place an order or as soon as a concern appears.', 'Αν έχετε ερώτηση σχετικά με παραγγελία, λεπτομέρεια πολιτικής ή τον τρόπο λειτουργίας του website, χρησιμοποιήστε τη σελίδα επικοινωνίας ώστε το κατάστημα να σας βοηθήσει άμεσα πριν κάνετε παραγγελία ή μόλις προκύψει κάποιο θέμα.') ?>>If you have a question about an order, a policy detail, or how the website works, please use the contact page so the shop can assist directly before you place an order or as soon as a concern appears.</p>
                </article>
            </div>
        </div>
    </section>
</main>

<?php include __DIR__ . '/include/footer.php'; ?>
</body>
</html>
